name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  RunTests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: Run the tests
      id: tests
      continue-on-error: true
      run: bundle exec rspec --order=rand -f j -o tmp/rspec_results.json
    - name: Bisect flaky specs
      if: steps.tests.outcome != 'success'
      run: cat tmp/rspec_results.json | jq '.seed'
